package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.Selenide.title;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GeneratedTests extends TestBase {
    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("v4scale contacts button test")
    void generatedTest() {
        step("Open 'https://v4scale.com/'", () -> {
            step("// todo: just add selenium action");
        });

        step("click at navigation menu", () -> {
            step("// todo: just add selenium action");
        });

        step("click at 'contacts' button", () -> {
            step("// todo: just add selenium action");
        });

        step("check if first address is 'Tel Aviv, Israel' and second is 'St. Petersburg, Russia'", () -> {
            step("// todo: just add selenium action");
        });

        step("check if business email is 'info@v4scale.com'", () -> {
            step("// todo: just add selenium action");
        });

        step("check if join us email is 'job@v4scale.com'", () -> {
            step("// todo: just add selenium action");
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://v4scale.com/'", () ->
            open("https://v4scale.com/"));

        step("Page title should have text 'V4Scale | V4Scale'", () -> {
            String expectedTitle = "V4Scale | V4Scale";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://v4scale.com/'", () ->
            open("https://v4scale.com/"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}